services:
  - type: web
    name: educonnect
    env: node
    buildCommand: |
      rm -rf node_modules
      rm -rf .next
      npm install
      npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 